inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - Gemfile.lock
    - '**/*.md'
    - bin/**/*
    - config/**/*.yml
    - config/environments/*.rb
    - script/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Exclude:
    - Gemfile

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# --- Lint ---

# --- Metrics ---

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120 # this isn't 1994

Metrics/MethodLength:
  Exclude:
    - robots/preservation/base.rb # execute_shell_command

# --- Naming ---

Naming/FileName:
  Exclude:
    - Capfile
    - Gemfile

# --- Performance ---

# --- RSpec ---

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/preservation/transfer_object_spec.rb # lots of expectations to set up for some specs

RSpec/MessageSpies:
  Enabled: false # receive is fine.  have_received is fine

RSpec/MultipleExpectations:
  Max: 4 # let's not be too pendantic about single expectation per test
  Exclude:
    - spec/preservation/transfer_object_spec.rb # lots of expectations to set up for some specs

# --- Style ---

Style/FrozenStringLiteralComment:
  Enabled: false # avoid cruft in our files for something that MAY be default in Ruby 3.0

Style/StringLiterals:
  Enabled: false # ' vs " isn't a big deal for readability or maintainability or execution time

Style/SymbolArray:
  Exclude:
    - Rakefile # because [:spec, :rubocop] isn't a big deal

Style/TernaryParentheses:
  Exclude:
    - config/boot.rb # line 37 is clearer with the parens
